### PR TITLE
added host_port feature

### PR DESCRIPTION
**Pull request by kael53**
added host_port feature as requested by issue-#13, made the least required changes to the Dockerfile and run script, to test without merging several extensive changes to the Dockerfile and run script must be made including copying app.js and webpack.config.js to the docker directory.

### CODE REVIEW

**Comment by wx9698** [comment]
@kael53 Cool! Thanks for the PR.

**Review by wx9698 — APPROVED** [review]

**Comment by kael53** [comment]
@wx9698 Thank you for the carlaviz! Can you please merge it?

**Comment by wx9698** [comment]
@kael53 Sure.

**Comment by kael53** [comment]
Thanks @wx9698 , it seems that the Dockerfile at the Docker Hub is not updated automatically, can you please also update that? Building it manually would take a lot of time and effort for all the users, thanks!

**Comment by wx9698** [comment]
@kael53 Sure thing. It is being built now.

**Pull request merged**
